#!/usr/bin/env bash

set -euo pipefail
set -x

declare -r esp=${ESP_PARTITION}
declare -r lvm=${CRYPT_PARTITION}
declare -r crypt_mapping_name=cryptlvm
declare -r volume_group_name=main

source "$(dirname "${BASH_SOURCE[0]}")/disk-config"

cryptsetup open "${lvm}" "${crypt_mapping_name}"

# Mount everything!
mkdir -p /mnt
mount "/dev/${volume_group_name}/root" /mnt

mkdir -p /mnt/home
mount "/dev/${volume_group_name}/home" /mnt/home

mkdir -p /mnt/boot
mount "${esp}" /mnt/boot
