#!/usr/bin/env bash
set -euo pipefail
set -x

# Import the config we need so that we crash early if it isn't there.
declare -r CONFIG_USER_NAME=${USER_NAME}

declare -r HOOK_DIR=$(readlink --canonicalize --no-newline "$(dirname "${BASH_SOURCE[0]}")")
declare -r HOME_DIR=$(getent passwd "${CONFIG_USER_NAME}" | cut -d: -f6)

main() {
    su --login "${CONFIG_USER_NAME}" -c "${HOOK_DIR}/stears-post-bootstrap-hook-ensure-dotfiles"
    # "${user_home_directory}/data/me/dotfiles/install"
}

xmonad() {
    packages+=(dmenu) 	  # For xmonad
    packages+=(clipmenu) 	# Seems a nice concept
    packages+=(stack) 	  # For xmonad
    packages+=(xmonad xmonad-contrib xmonad-utils)
}

main "${@}"
