#!/usr/bin/env bash
# NOTE: this script gets run as the target user, not as root

set -euo pipefail
set -x

declare -r DOTFILES_REPO=git@github.com:philipstears/dotfiles
declare -r PROJECT_REPO=git@github.com:philipstears/project

main() {
    mkdir -p "${HOME}/data/me"

    # Make sure we've got access to the SSH key before doing stuff with git
    eval "$(ssh-agent)"
    ssh-add

    if [[ -d "${HOME}/data/me/dotfiles" ]]; then
        ( cd "${HOME}/data/me/dotfiles" && git pull )
    else
        git clone -b arch -- "${DOTFILES_REPO}" "${HOME}/data/me/dotfiles"
    fi

    if [[ -d "${HOME}/data/me/project" ]]; then
        ( cd "${HOME}/data/me/project" && git pull )
    else
        git clone "${PROJECT_REPO}" "${HOME}/data/me/project"
    fi

    ln -sf "${HOME}/data/me/project/project" "${HOME}/.local/bin/project"
}

main "${@}"
